#!/usr/bin/env python3
"""build_taint_register.py -- generate eval/capability-map/TAINT-REGISTER-v1.yaml.

Read-only over all evidence.  Standard library plus PyYAML.  Deterministic:
running it twice produces a byte-identical file, because nothing in the output
depends on the wall clock, on dictionary iteration order, or on the order in
which the filesystem returns names.

What it does
------------
For every one of the cells in `eval/capability-map/ROUTING-EVIDENCE-MAP-v0.yaml`
it records, in machine-readable form:

  * which named problems (from a closed vocabulary) touched that cell -- the
    history is preserved even where a ruling has since disposed of it,
  * which Controller rulings of 14 September 2026 dispose of those problems
    (`rulings_applied`) and, for the cells C-4 names, how (`c4_disposition`),
  * how many of its draws are settled (counted under the frozen rule), how
    many were excluded before anything was sent, and how many re-sends and
    smoke draws are carried as descriptive only,
  * what the sealed results files recorded versus what the literal frozen
    elimination rule produces (the strict reading is the counting one under
    C-6b; the lenient reading is kept so the reader can see what the runs did),
  * whether a production router may rest a route decision on it today.

It decides nothing.  It applies the rulings exactly as recorded in
coordination/decisions/CONTROLLER-AUDIT-CLOSEOUT-EVIDENCE-RULINGS-2026-09-14.md
and says where a question remains open.

Safety
------
The register is only meaningful against the exact map it was built from, so the
generator refuses to run when the map's sha256 is not the one recorded below.
That way the register can never silently drift from the map.

Usage
-----
    python3 coordination/audits/tools/build_taint_register.py [--check]

`--check` regenerates into memory and reports whether the committed register
would change, without writing anything.

No model call, no network call, no cloud command.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import importlib.util
import os
import sys

import yaml

# --------------------------------------------------------------------------
# the exact map this generator was built against
# --------------------------------------------------------------------------

MAP_PATH = os.path.join("eval", "capability-map", "ROUTING-EVIDENCE-MAP-v0.yaml")
# 14 Sep 2026: the map was regenerated by design (the rulings below); the
# previous value, against which the 10 Sep register was built, was
# 50f0d355440027f7cee8a9b146577f0850ab55f1dd0f6d6ddff0c531f8028e6f.
MAP_SHA256 = "8df6ead0712d6b67070e7475ab56aa12be7f9480916a79a273bec5ff25c7f707"
MAP_CELL_COUNT = 61

OUT_PATH = os.path.join("eval", "capability-map", "TAINT-REGISTER-v1.yaml")

RECOMPUTE_PATH = os.path.join(
    "coordination", "audits", "tools", "recompute_elimination.py"
)
RULES_PATH = os.path.join(
    "eval", "empirical-planning", "STAGE-A-FREEZE-2026-09", "ELIMINATION-RULES.md"
)
RUNS_DIR = os.path.join("eval", "experiments", "EVAL-040", "runs")

RECOMPUTE_AUDIT = "coordination/audits/AUDIT-2026-09-10-EVIDENCE-RECOMPUTE.md"
REPORT_A = "coordination/audits/AUDIT-2026-09-10-REPORT-A.md"
REPORT_B = "coordination/audits/AUDIT-2026-09-10-REPORT-B.md"
DECISIONS = "coordination/audits/AUDIT-2026-09-10-CONTROLLER-DECISIONS.md"

# Report A, "Missing scientific/product proof" item 4 ("More than two draws for
# decisions that materially control customer routing") and Report B part 4 item
# 1 plus its P1 ("the map's rules rest on four draws per cell instead of two").
# Four settled draws is therefore the floor a cell must clear before its number
# is treated as more than directional.  This is a threshold quoted from the two
# audits, not a judgement made here.
MIN_SETTLED_DRAWS = 4

RULINGS_RECORD = (
    "coordination/decisions/CONTROLLER-AUDIT-CLOSEOUT-EVIDENCE-RULINGS-2026-09-14.md"
)

# The Controller's rulings of 14 September 2026, verbatim.  Every status in this
# file follows from applying them literally; none of them was decided here.
RULINGS = collections.OrderedDict(
    [
        (
            "C-3",
            "Apply the frozen elimination rule literally. Infrastructure/request "
            "failures count wherever the preregistered rule says they count. Any "
            "different treatment must be prospective.",
        ),
        (
            "C-4",
            "any Stage-A human-routing cell affected by duplicated dispatched trial "
            "identities, smoke-as-extra-draw, or infrastructure exclusions contrary "
            "to E1/E2 is descriptive product-learning evidence only, until "
            "recomputed or cleanly replaced. Deterministic Registry evidence is "
            "untouched.",
        ),
        (
            "C-6b",
            "STRICT interpretation. A failed Wan 2 draw remains a failure under the "
            "frozen experiment. The six HTTP-422 failures are not erased by later "
            "undeclared re-sends. RR-16 therefore cannot remain clean Stage-A "
            "image-to-video routing truth. Successful re-sends may remain "
            "clearly-labelled descriptive product evidence. Do not delete them.",
        ),
        (
            "C-6c",
            "Re-key exact-text mechanisms. These are DIFFERENT route mechanisms: A. "
            "the generative model itself draws exact text; B. the generative model "
            "produces a textless visual plate and deterministic code composes exact "
            "text afterward. They must have different route identities. Rewrite "
            "RR-1 so its evidence says precisely what was accepted. Never imply the "
            "model rendered the accepted exact copy when code did.",
        ),
        (
            "C-6d",
            "Elimination is per (route, question), exactly as frozen E4. Recompute "
            "affected derivative cells accordingly.",
        ),
    ]
)

# One plain-English gloss per ruling, so a non-engineer reading a cell's
# `reason` is told what the ruling settled for that cell.
RULING_GLOSS = {
    "C-3": "the planned denominator is kept and every refusal or error is counted",
    "C-4": "the cell was recomputed under the frozen rule, so its number stands",
    "C-6b": "the first sending of a draw is the one that counts; a re-send is descriptive only",
    "C-6c": "the code-overlay judging is its own route identity, apart from the bare plate",
    "C-6d": "the route is eliminated, or kept, on its question as a whole, not case by case",
}

# The problems C-4 names, and the ruling that disposes of each problem.
C4_PROBLEMS = ("duplicate_dispatched_identity", "smoke_shared_identity", "infra_refusal_excluded")
PROBLEM_RULING = {
    "infra_refusal_excluded": ["C-3", "C-4"],
    "denominator_convention_differs": ["C-3"],
    "duplicate_dispatched_identity": ["C-4", "C-6b"],
    "redo_undeclared": ["C-6b"],
    "smoke_shared_identity": ["C-4"],
    "contradictory_verdicts": ["C-6c"],
    "judged_stricter_than_contract": ["C-6d"],
}
ALL_RULINGS = list(RULINGS)

PROBLEM_VOCABULARY = [
    "duplicate_dispatched_identity",
    "smoke_shared_identity",
    "redo_undeclared",
    "infra_refusal_excluded",
    "denominator_convention_differs",
    "contradictory_verdicts",
    "judged_stricter_than_contract",
]

STATUS_VOCABULARY = [
    "clean_observed",
    "directional_only",
    "awaiting_controller_ruling",
    "method_tainted",
    "insufficient",
]


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def repo_root() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    guess = os.path.abspath(os.path.join(here, "..", "..", ".."))
    if os.path.isdir(os.path.join(guess, RUNS_DIR)):
        return guess
    cwd = os.path.abspath(os.getcwd())
    if os.path.isdir(os.path.join(cwd, RUNS_DIR)):
        return cwd
    sys.stderr.write(
        "cannot locate the repository root: %s not found under %s or %s\n"
        % (RUNS_DIR, guess, cwd)
    )
    raise SystemExit(2)


def sha256_of(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_recompute(root: str):
    """Import the audit's recompute tool as a library.  It is the single source
    of every number here; this generator adds no arithmetic of its own."""
    path = os.path.join(root, RECOMPUTE_PATH)
    sys.dont_write_bytecode = True
    spec = importlib.util.spec_from_file_location("recompute_elimination", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def guard_map_version(root: str) -> None:
    path = os.path.join(root, MAP_PATH)
    if not os.path.isfile(path):
        sys.stderr.write("routing evidence map not found at %s\n" % MAP_PATH)
        raise SystemExit(2)
    actual = sha256_of(path)
    if actual != MAP_SHA256:
        sys.stderr.write(
            "REFUSING TO RUN.\n"
            "  %s has changed since this generator was written.\n"
            "    expected sha256 : %s\n"
            "    actual   sha256 : %s\n"
            "  The taint register must never drift from the map it describes.\n"
            "  Re-read the map, update MAP_SHA256 in this file deliberately,\n"
            "  and re-check every cell before regenerating.\n"
            % (MAP_PATH, MAP_SHA256, actual)
        )
        raise SystemExit(3)


# --------------------------------------------------------------------------
# the plain-English header written into the register itself
# --------------------------------------------------------------------------

HEADER_COMMENT = """\
# =============================================================================
# TAINT-REGISTER-v1 -- what each number in the routing map is worth
# =============================================================================
#
# READ THIS FIRST. It is written for a reader who is not an engineer.
#
# The routing map next door lists, for every job the project can do, which
# model routes were tried and how many of their outputs were accepted. This
# file sits beside it and answers a different question about each of those
# entries: HOW MUCH WEIGHT CAN THIS NUMBER TAKE?
#
# An audit on 10 September 2026 found that some numbers in the map were
# produced under a counting rule that was not the one written down before the
# money was spent, that some draws were sent twice under the same name, and
# that in one place the same four draws carried two different answers. On
# 14 September 2026 the Controller ruled on every one of those points
# (rulings C-3, C-4, C-6b, C-6c and C-6d, quoted verbatim under `rulings`
# below), and the map was regenerated so that every human-acceptance number
# is now COMPUTED under the frozen rule, applied literally, from the sealed
# run directories. This file records, per entry, which problems touched it,
# which ruling disposed of each, and what the number is now worth.
#
# None of that means the earlier work was wasted. It means a machine may use
# a number to choose a route for a paying customer only where the number
# reproduces from the sealed files under the rule that was frozen first.
#
# -----------------------------------------------------------------------------
# THE FIVE STATUSES, IN PLAIN ENGLISH
# -----------------------------------------------------------------------------
#
# clean_observed
#   WHAT IT MEANS: the literal frozen rule reproduces the number from the
#     sealed files; every named problem touching the entry has been disposed
#     of by a Controller ruling listed in `rulings_applied` and the entry has
#     been recomputed; at least four settled draws sit behind it. A settled
#     draw is one whose FIRST sending has a counted outcome -- an accept, a
#     reject, or a refusal / error counted as a failure. Re-sends and smoke
#     draws are never settled; they are listed as descriptive.
#   WHAT IT DOES NOT MEAN: it does not mean the route is good, cheap, or the
#     best choice; it does not mean the sample is large enough to be reliable in
#     a statistical sense; and it does NOT mean the route is cleared for launch
#     traffic. Four to eight draws judged by one person over two evenings is
#     honest evidence, not proof. An eliminated route can be clean_observed --
#     its number is clean -- and still carry production_use_allowed: false.
#
# directional_only
#   WHAT IT MEANS: the number reproduces and every problem is disposed of, but
#     it rests on fewer than four settled draws. It is a signal, not a
#     measurement.
#   WHAT IT DOES NOT MEAN: it does not mean the number is wrong. It means a
#     route that scored 2 out of 2 may simply be a coin that landed twice, so
#     the number should not decide a route on its own.
#
# awaiting_controller_ruling
#   WHAT IT MEANS: a specific question is still open and its answer changes the
#     entry's number, its keep / drop verdict, or whether it may be counted.
#     Since the rulings of 14 September 2026 NO entry carries this status: C-3,
#     C-4, C-6b, C-6c and OPEN-1 (closed by C-6d) are all ruled. The status
#     stays in the vocabulary so that a future unruled problem has somewhere
#     honest to go.
#
# method_tainted
#   WHAT IT MEANS: a known problem affects the number and no ruling can repair
#     it -- the only fix is to run the draws again, cleanly.
#   WHAT IT DOES NOT MEAN: it does not mean anyone acted in bad faith, and it
#     does not mean what was learned from those outputs is untrue. It means the
#     number cannot be defended. No entry carries it today (see
#     NOTE-WHY-NO-METHOD-TAINTED-CELLS).
#
# insufficient
#   WHAT IT MEANS: there is not enough evidence here to say anything at all.
#   WHAT IT DOES NOT MEAN: it does not mean the route failed.
#
# -----------------------------------------------------------------------------
# WHAT THIS FILE DELIBERATELY DOES NOT CONTAIN
# -----------------------------------------------------------------------------
#
# There is no launch-eligibility status anywhere in this file, and there never
# will be. Whether an entry may carry real customer traffic is a Controller
# ruling plus a runtime decision. This file only reports the state of the
# evidence. The runtime's own policy profile decides which of these statuses it
# is willing to route on automatically -- for example, a cautious profile might
# auto-route only on `clean_observed` and send everything else to a person.
#
# `production_use_allowed` is this file's reading of the evidence, not a
# permission:
#     true         the evidence behind this entry is settled and reproduces
#     manual_only  a person must look before this entry decides anything
#     false        do not rest a route decision on this entry (an eliminated
#                  route is always false, whatever its status)
#
# `replacement_needed: true` means the route's elimination rests on failures
# the run itself classified as infrastructure or request-shape faults, now
# counted under C-3 / C-6b. No ruling can re-test the route; only a clean
# rerun (Controller item C-15) can.
#
# `c4_disposition` appears on every entry C-4 names (a duplicated dispatched
# identity, a smoke draw sharing its name, or an infrastructure exclusion):
#     recomputed_under_frozen_rule            the number shown is the literal
#                                             recompute and stands
#     descriptive_only_pending_clean_replacement
#                                             the recompute could not produce a
#                                             frozen-rule number (none today)
#
# Nothing in this file was decided by its author. Every ruling applied is
# quoted; every question still open is named and left open.
#
# Generated by coordination/audits/tools/build_taint_register.py -- regenerate,
# do not hand-edit. The generator refuses to run if the routing map has changed.
# =============================================================================
"""


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------


def cell_problems(ctx, key, trials, occurrences, verdicts, map_cell, rec_list, literal, collision):
    """The named problems touching one cell, drawn only from the closed
    vocabulary.  Every branch names the sealed evidence it rests on."""
    problems = set()
    evidence = []

    # -- duplicated dispatched identities and undeclared re-dos -------------
    for trial_id in sorted(trials):
        rows = occurrences.get(trial_id) or []
        # C-6c: a code-overlay judging is a different route identity, not a
        # second dispatch of the same draw; it is recorded under
        # contradictory_verdicts below, never as a duplicate or a re-do
        non_smoke = [r for r in rows if r["kind"] not in ("smoke", ctx.DISTINCT_MECHANISM)]
        smoke = [r for r in rows if r["kind"] == "smoke"]
        if len(non_smoke) > 1:
            problems.add("duplicate_dispatched_identity")
            evidence.append(
                "%s was dispatched in %s"
                % (trial_id, " then ".join(r["run_id"] for r in non_smoke))
            )
        if smoke:
            problems.add("smoke_shared_identity")
            evidence.append(
                "%s was also dispatched, paid for and never judged in %s"
                % (trial_id, ", ".join(r["run_id"] for r in smoke))
            )
        if any(r["kind"] == "redo (undeclared)" for r in non_smoke):
            problems.add("redo_undeclared")
            evidence.append(
                "%s was re-sent in %s, whose PLAN.yaml records redo_of: null"
                % (
                    trial_id,
                    ", ".join(
                        r["run_id"]
                        for r in non_smoke
                        if r["kind"] == "redo (undeclared)"
                    ),
                )
            )

    # -- contradictory verdicts on one identity -----------------------------
    for trial_id in sorted(trials):
        if trials[trial_id].get("conflict"):
            problems.add("contradictory_verdicts")
            evidence.append(
                "%s carries two different Controller verdicts in two runs" % trial_id
            )
        # C-6c history: the identity was judged under two mechanisms (the bare
        # plate in one run, code-composed text in another).  The recompute now
        # keeps them apart as two route identities; the problem is recorded so
        # the history is not lost, and C-6c is the ruling that disposes of it.
        rows = occurrences.get(trial_id) or []
        kinds = {r["kind"] for r in rows}
        if ctx.DISTINCT_MECHANISM in kinds and len(kinds - {"smoke"}) > 1:
            problems.add("contradictory_verdicts")
            bare = [r for r in rows if r["kind"] not in ("smoke", ctx.DISTINCT_MECHANISM)]
            comp = [r for r in rows if r["kind"] == ctx.DISTINCT_MECHANISM]
            v_bare = ", ".join(str((verdicts.get((r["run_id"], trial_id)) or {}).get("verdict")) for r in bare)
            v_comp = ", ".join(str((verdicts.get((r["run_id"], trial_id)) or {}).get("verdict")) for r in comp)
            evidence.append(
                "%s was judged in %s as the provider's bare plate (%s) and in %s as the "
                "code-composed output under layout %s (%s), both recorded under one trial "
                "id. C-6c re-keys the second as route identity %s, so the two judgings are "
                "two route mechanisms, not one contested draw"
                % (
                    trial_id,
                    ", ".join(r["run_id"] for r in bare),
                    v_bare,
                    ", ".join(r["run_id"] for r in comp),
                    ctx.COMPOSITE_LAYOUT,
                    v_comp,
                    key[1] if key[1].endswith(ctx.CODE_OVERLAY_SUFFIX) else key[1] + ctx.CODE_OVERLAY_SUFFIX,
                )
            )
    if collision:
        problems.add("contradictory_verdicts")
        evidence.append(
            "this cell shares route_key %r and arm %r with map cell %r, and the two "
            "carry different acceptance numbers" % (key[1], key[2], collision)
        )

    # -- infrastructure refusals excluded from the count --------------------
    rec_infra = sum((e.get("infra_refusals_not_counted") or 0) for _d, e in rec_list)
    rec_refusals = sum((e.get("refusals_or_errors") or 0) for _d, e in rec_list)
    if rec_list and (rec_infra > 0 or literal["strict_refusals"] > rec_refusals):
        problems.add("infra_refusal_excluded")
        evidence.append(
            "the sealed results file records refusals_or_errors=%d and "
            "infra_refusals_not_counted=%d where the literal rule counts %d "
            "refusal(s) or error(s)"
            % (rec_refusals, rec_infra, literal["strict_refusals"])
        )

    # -- denominator conventions -------------------------------------------
    map_trials = ((map_cell.get("human_blind_acceptance") or {}).get("trials"))
    rec_judged = [e.get("n_judged") for _d, e in rec_list if e.get("n_judged")]
    rec_planned = sum((e.get("n_planned") or 0) for _d, e in rec_list)
    if isinstance(map_trials, int) and map_trials != literal["n_planned"]:
        problems.add("denominator_convention_differs")
        evidence.append(
            "the routing map divides by %d where the frozen rule's planned "
            "denominator is %d" % (map_trials, literal["n_planned"])
        )
    if any(n != literal["n_planned"] for n in rec_judged):
        problems.add("denominator_convention_differs")
        evidence.append(
            "the sealed results file divides by n_judged=%s where the frozen "
            "rule's planned denominator is %d"
            % (", ".join(str(n) for n in rec_judged), literal["n_planned"])
        )
    if rec_list and rec_planned and rec_planned != literal["n_planned"]:
        problems.add("denominator_convention_differs")
        evidence.append(
            "the sealed results file's elimination entries plan %d trial(s) "
            "where the plans hold %d" % (rec_planned, literal["n_planned"])
        )

    # -- elimination applied at a stricter scope than the frozen contract ---
    if len(rec_list) > 1:
        problems.add("judged_stricter_than_contract")
        evidence.append(
            "the run eliminated this route case by case (%d separate entries) "
            "where rule E4 makes elimination per (route, question)" % len(rec_list)
        )

    return sorted(problems), sorted(set(evidence))


def classify_trials(ctx, trials, occurrences, verdicts):
    """Split a cell's logical trials into settled, excluded and descriptive
    under the rulings.

    settled     -- the FIRST sending of the draw has a counted outcome under the
                   literal rule: an accept, a reject, or a refusal / error
                   counted as a failure (C-3, C-6b strict).  A draw the run
                   kept out of its own denominator is settled here, because
                   the frozen rule counts it.
    excluded    -- the harness refused before anything was sent: no provider
                   behaviour observed, no money moved, not a draw.
    descriptive -- attempts that are never counted: a re-send of a draw whose
                   first sending already settled it (C-6b), and a smoke draw
                   that reused the identity (C-4).  Listed per attempt.

    Returns (settled, excluded, descriptive_attempts, infra_classified) where
    infra_classified is the set of settled trial ids whose counted failure the
    run itself recorded as an infrastructure / request-shape fault (or did not
    record in any results file at all)."""
    settled, excluded, descriptive = [], [], []
    infra = set()
    for trial_id in sorted(trials):
        trial = trials[trial_id]
        rows = occurrences.get(trial_id) or []
        if trial["strict"] == "pre_dispatch_refusal":
            excluded.append((trial_id, "harness refused before anything was sent"))
            continue
        attempts = trial["attempts"]
        first = attempts[0]
        later = attempts[1:]
        why = "first sending %s:%s%s counts under the frozen rule" % (
            first["run_id"],
            first["status"],
            "/" + str(first["error_class"]) if first["error_class"] else "",
        )
        if later:
            why += "; %d later re-send(s) descriptive only (C-6b)" % len(later)
        settled.append((trial_id, why))
        if first["status"] in ctx.ERROR_STATUSES:
            judged = verdicts.get((first["run_id"], trial_id))
            basis = str((judged or {}).get("verdict_basis") or "")
            if judged is None or "not_counted" in basis:
                infra.add(trial_id)
        for attempt in later:
            descriptive.append(
                (
                    trial_id,
                    attempt["run_id"],
                    "resend",
                    "re-sent after the first sending settled the draw; descriptive product evidence, not counted (C-6b)",
                )
            )
        for row in rows:
            if row["kind"] == "smoke":
                descriptive.append(
                    (
                        trial_id,
                        row["run_id"],
                        "smoke",
                        "a smoke draw that reused this identity; never judged, never counted (C-4)",
                    )
                )
    return settled, excluded, descriptive, infra


def rulings_for(problems) -> list:
    """The rulings that dispose of the named problems, in ruling order."""
    out = []
    for r in ALL_RULINGS:
        if any(r in PROBLEM_RULING.get(p, []) for p in problems):
            out.append(r)
    return out


def decide_status(problems, settled_n, has_trials, reproduces):
    """The status, the blocking ruling and the blocking open question.

    Every problem in the closed vocabulary is now disposed of by a ruling
    (PROBLEM_RULING), so no cell may remain awaiting_controller_ruling for
    C-3 / C-4 / C-6b / C-6c or OPEN-1.  A problem outside that table would be
    method_tainted -- there is none today.  `reproduces` is whether the
    number the map carries is the literal recompute; it always is, because
    the map is generated from the same tool, and the builder refuses to run
    otherwise.
    """
    if not has_trials:
        return "insufficient", None, None
    unruled = [p for p in problems if p not in PROBLEM_RULING]
    if unruled or not reproduces:
        return "method_tainted", None, None
    if settled_n < MIN_SETTLED_DRAWS:
        return "directional_only", None, None
    return "clean_observed", None, None


# --------------------------------------------------------------------------
# build
# --------------------------------------------------------------------------


def build(root: str) -> str:
    rc = load_recompute(root)

    cwd = os.getcwd()
    os.chdir(root)
    try:
        runs = rc.load_runs(root)
        occurrences = rc.build_occurrences(runs)
        verdicts = rc.judged_verdicts(runs)
        groups = rc.build_groups(runs, occurrences, verdicts)
        recorded = rc.recorded_entries(runs, list(groups.keys()))
        with open(MAP_PATH, "r", encoding="utf-8") as handle:
            cmap = yaml.safe_load(handle)
        map_sha = sha256_of(MAP_PATH)
        recompute_sha = sha256_of(RECOMPUTE_PATH)
        rules_sha = sha256_of(RULES_PATH)
    finally:
        os.chdir(cwd)

    # (route_key, arm) pairs that more than one cell in the same question uses.
    # C-6c gave the code-overlay cell its own route identity, so this is empty
    # today; the check stays so a future collision is still made visible.
    collisions = {}
    for question in sorted(cmap["questions"]):
        by_pair = collections.defaultdict(list)
        for cell_name, cell in sorted(cmap["questions"][question]["cells"].items()):
            by_pair[(cell.get("route_key"), cell.get("arm"))].append(cell_name)
        for pair, names in by_pair.items():
            if len(names) > 1:
                for name in names:
                    collisions[(question, name)] = sorted(n for n in names if n != name)

    cells_out = []
    for question in sorted(cmap["questions"]):
        for cell_name in sorted(cmap["questions"][question]["cells"]):
            cell = cmap["questions"][question]["cells"][cell_name]
            route_key = cell.get("route_key")
            arm = cell.get("arm")
            key = (question, route_key, arm)
            trials = groups.get(key) or {}
            rec_list = recorded.get(key) or []
            hba = cell.get("human_blind_acceptance") or {}

            # every number from the one implementation of the arithmetic
            numbers = rc.cell_numbers(runs, groups, occurrences, key)
            n_planned = numbers["n_planned"]
            strict_acc = numbers["accepts"]
            strict_ref = numbers["refusals_or_errors"]
            strict_by = numbers["eliminated_by"]
            lenient_acc = numbers["lenient"]["accepts"]
            lenient_ref = numbers["lenient"]["refusals_or_errors"]
            lenient_by = numbers["lenient"]["eliminated_by"]
            literal = {
                "n_planned": n_planned,
                "strict_accepts": strict_acc,
                "strict_refusals": strict_ref,
                "lenient_accepts": lenient_acc,
                "lenient_refusals": lenient_ref,
            }

            collision_names = collisions.get((question, cell_name))
            collision = collision_names[0] if collision_names else None

            problems, problem_evidence = cell_problems(
                rc, key, trials, occurrences, verdicts, cell, rec_list, literal, collision
            )
            settled, excluded, descriptive, infra_classified = classify_trials(
                rc, trials, occurrences, verdicts
            )
            pre_dispatch_n = sum(
                1 for t in trials.values() if t.get("pre_dispatch_refusal_runs")
            )

            # What the sealed results file recorded (transparency; never counted).
            res = rc.recorded_summary(runs, rec_list)
            res_accepts, res_den, res_elim = res["accepts"], res["trials"], res["eliminated"]
            if rec_list:
                results_verdict = (
                    "not_recorded" if res_elim is None
                    else ("eliminated:%s" % "+".join(res["eliminated_by"]) if res_elim else "kept")
                )
                results_number = "%d/%d" % (res_accepts, res_den)
            else:
                results_verdict = "not_recorded"
                results_number = None

            # What the routing map carries -- since 14 Sep 2026 the literal
            # recompute itself; the builder refuses to run if it is not.
            map_accepts = hba.get("accepts")
            map_den = hba.get("trials")
            map_elim = hba.get("eliminated")
            map_by = sorted(hba.get("eliminated_by") or [])
            if map_accepts is None:
                map_verdict, map_number = "not_recorded", None
            else:
                map_verdict = "eliminated:%s" % "+".join(map_by) if map_elim else "kept"
                map_number = "%s/%s" % (map_accepts, map_den)

            literal_verdict = {
                "strict": "eliminated:%s" % "+".join(strict_by) if strict_by else "kept",
                "lenient": "eliminated:%s" % "+".join(lenient_by)
                if lenient_by
                else "kept",
                "strict_number": "%d/%d" % (strict_acc, n_planned),
                "lenient_number": "%d/%d" % (lenient_acc, n_planned),
                "readings_agree": bool(strict_by) == bool(lenient_by)
                and strict_acc == lenient_acc,
                "counting_reading": "strict (C-6b)",
            }

            reproduces = (
                map_accepts is None
                or (
                    map_accepts == strict_acc
                    and map_den == n_planned
                    and bool(map_elim) == bool(strict_by)
                )
            )
            if not reproduces:
                raise SystemExit(
                    "internal inconsistency: %s/%s carries %s in the map but the literal "
                    "recompute gives %s; the map must be regenerated before this register."
                    % (question, cell_name, map_number, literal_verdict["strict_number"])
                )

            # does the sealed results file agree with the literal rule?
            if res_elim is None:
                verdict_changes = None
            else:
                verdict_changes = bool(strict_by) != res_elim
            number_changes = None
            if res_accepts is not None:
                number_changes = res_accepts != strict_acc or (
                    res_den is not None and res_den != n_planned
                )

            eliminated = bool(strict_by)
            rulings_applied = rulings_for(problems)
            status, blocking_ruling, blocking_open = decide_status(
                problems, len(settled), bool(trials), reproduces
            )

            if eliminated:
                production = False
            elif status == "clean_observed":
                production = True
            elif status == "directional_only":
                production = "manual_only"
            elif status == "awaiting_controller_ruling":
                production = "manual_only"
            else:
                production = False

            # C-4 disposition: the number shown is the literal recompute.
            c4 = None
            if any(p in C4_PROBLEMS for p in problems):
                c4 = (
                    "recomputed_under_frozen_rule"
                    if reproduces
                    else "descriptive_only_pending_clean_replacement"
                )

            # replacement_needed: the elimination rests on failures the run
            # itself classified as infrastructure / request-shape faults.  Test:
            # take those failures out of both the numerator and the planned
            # denominator; if the route would then survive, the failures decide
            # the verdict, and only a clean rerun (C-15) can re-test the route.
            infra_n = len(infra_classified)
            rests_on_infra = False
            if eliminated and infra_n:
                without = rc.verdict_for(n_planned - infra_n, strict_ref - infra_n, strict_acc)
                rests_on_infra = not without
            replacement_needed = bool(status in ("method_tainted", "insufficient") or rests_on_infra)

            # one plain sentence
            glossed = "; ".join("%s (%s)" % (r, RULING_GLOSS[r]) for r in rulings_applied)
            if status == "clean_observed" and production is True:
                reason = (
                    "The literal frozen rule reproduces %s from the sealed files on %d "
                    "settled draws%s."
                    % (
                        map_number or literal_verdict["strict_number"],
                        len(settled),
                        ("; " + glossed) if glossed else ", and no named problem ever touched it",
                    )
                )
            elif eliminated:
                reason = (
                    "eliminated on its question under the frozen rule (%s): %s on %d settled "
                    "draw(s)%s."
                    % (
                        "+".join(strict_by),
                        literal_verdict["strict_number"],
                        len(settled),
                        ("; " + glossed) if glossed else "",
                    )
                )
                if rests_on_infra:
                    reason += (
                        " The elimination rests on %d failure(s) the run classified as an "
                        "infrastructure / request-shape fault, now counted under C-3 / C-6b; "
                        "a clean rerun (Controller item C-15) is the only thing that could "
                        "re-test this route." % infra_n
                    )
            elif status == "directional_only":
                reason = (
                    "The number reproduces on %d settled draw(s), below the four the audits "
                    "ask for before a number decides a customer route%s."
                    % (len(settled), ("; " + glossed) if glossed else "")
                )
            elif status == "awaiting_controller_ruling":
                named = blocking_ruling or blocking_open
                reason = "Open question %s decides this cell." % named
            elif status == "method_tainted":
                reason = (
                    "%s affects the number and no ruling disposes of it; only fresh "
                    "draws can." % ", ".join(problems)
                )
            else:
                reason = "There is no judged evidence behind this cell."

            # sealed sources for every count above
            run_ids, plans, results_files, run_logs = set(), set(), set(), set()
            for trial_id in trials:
                for row in occurrences.get(trial_id) or []:
                    run_ids.add(row["run_id"])
            if key[1] and key[1].endswith(rc.CODE_OVERLAY_SUFFIX):
                # the code-overlay identity's attempts are only the composite run's
                run_ids = {
                    r for r in run_ids if runs[r].get("composite_layout") or runs[r]["mode"] == "smoke"
                }
            elif any(runs[r].get("composite_layout") for r in run_ids):
                run_ids = {r for r in run_ids if not runs[r].get("composite_layout")}
            for run_id in sorted(run_ids):
                plans.add(os.path.join(RUNS_DIR, run_id, "PLAN.yaml"))
                run_logs.add(os.path.join(RUNS_DIR, run_id, "RUN-LOG.jsonl"))
                if runs[run_id].get("results_path"):
                    results_files.add(runs[run_id]["results_path"])
            for run_dir, _entry in rec_list:
                if runs[run_dir].get("results_path"):
                    results_files.add(runs[run_dir]["results_path"])

            # F-7: the image rounds committed to a salted fingerprint of the blind
            # mapping; the video and audio rounds did not.  Read straight from the
            # sealed results files, never asserted here.
            commitments = set()
            for run_id in sorted(run_ids):
                results = runs[run_id].get("results")
                if results and "commitment_verified" in results:
                    commitments.add(bool(results.get("commitment_verified")))
            if commitments == {True}:
                blinding = True
            elif commitments == {False}:
                blinding = False
            elif commitments:
                blinding = "mixed"
            else:
                blinding = None

            trial_rows = []
            for bucket, items in (("clean", settled), ("excluded", excluded)):
                for trial_id, why in items:
                    attempts = []
                    for row in occurrences.get(trial_id) or []:
                        if key[1] and key[1].endswith(rc.CODE_OVERLAY_SUFFIX):
                            if not row["composite_layout"] and row["kind"] != "smoke":
                                continue
                        elif row["composite_layout"]:
                            continue
                        judged = verdicts.get((row["run_id"], trial_id))
                        first = trials[trial_id]["attempts"][0]["run_id"] if trials[trial_id]["attempts"] else None
                        attempts.append(
                            {
                                "run_id": row["run_id"],
                                "kind": row["kind"],
                                "status": row["status"],
                                "error_class": row["error_class"],
                                "verdict": (judged or {}).get("verdict"),
                                "in_results_file": judged is not None,
                                "counted": row["kind"] != "smoke" and row["run_id"] == first,
                            }
                        )
                    trial_rows.append(
                        {
                            "trial_id": trial_id,
                            "counted_as": bucket,
                            "strict": trials[trial_id]["strict"],
                            "lenient": trials[trial_id]["lenient"],
                            "why": why,
                            "attempts": attempts,
                        }
                    )
            trial_rows.sort(key=lambda r: (r["counted_as"], r["trial_id"]))
            descriptive_rows = [
                {"trial_id": t, "run_id": r, "kind": k, "why": w}
                for t, r, k, w in sorted(descriptive)
            ]

            entry = collections.OrderedDict()
            entry["cell_key"] = "%s/%s" % (question, cell_name)
            entry["question"] = question
            entry["route_key"] = route_key
            entry["arm"] = arm
            entry["map_cell_name"] = cell_name
            entry["text_mechanism"] = cell.get("text_mechanism")
            entry["run_ids"] = sorted(run_ids)
            entry["problem"] = problems
            entry["problem_evidence"] = problem_evidence
            entry["rulings_applied"] = rulings_applied
            if c4 is not None:
                entry["c4_disposition"] = c4
            entry["clean_trials"] = len(settled)
            entry["excluded_trials"] = len(excluded)
            entry["descriptive_trials"] = len({t for t, _r, _k, _w in descriptive})
            entry["descriptive_resend_attempts"] = sum(1 for _t, _r, k, _w in descriptive if k == "resend")
            entry["smoke_attempts_excluded"] = sum(1 for _t, _r, k, _w in descriptive if k == "smoke")
            entry["pre_dispatch_refusal_trials"] = pre_dispatch_n
            entry["planned_trials_frozen_rule"] = n_planned
            entry["map_reported_trials"] = map_den
            entry["map_reported_accepts"] = map_accepts
            entry["recorded_verdict"] = map_verdict
            entry["recorded_number"] = map_number
            entry["recorded_in_results_file"] = collections.OrderedDict(
                [
                    ("verdict", results_verdict),
                    ("number", results_number),
                    ("files", res["files"]),
                ]
            )
            entry["literal_verdict"] = literal_verdict
            entry["verdict_changes"] = verdict_changes
            entry["number_changes"] = number_changes
            entry["eliminated"] = eliminated
            entry["eliminated_by"] = list(strict_by)
            entry["evidence_status"] = status
            entry["production_use_allowed"] = production
            entry["blocking_ruling"] = blocking_ruling
            entry["blocking_open_question"] = blocking_open
            entry["replacement_needed"] = replacement_needed
            entry["reason"] = reason
            if collision_names:
                entry["shares_route_key_and_arm_with"] = [
                    "%s/%s" % (question, n) for n in collision_names
                ]
            entry["blinding_commitment_verified"] = blinding
            entry["sources"] = collections.OrderedDict(
                [
                    ("plans", sorted(plans)),
                    ("results", sorted(results_files)),
                    ("run_logs", sorted(run_logs)),
                    ("elimination_rules", RULES_PATH),
                    ("rulings_record", RULINGS_RECORD),
                ]
            )
            entry["trials"] = trial_rows
            entry["descriptive_attempts"] = descriptive_rows
            cells_out.append(entry)

    cells_out.sort(key=lambda c: c["cell_key"])

    # ---------------------------------------------------------------- summary
    by_status = collections.Counter(c["evidence_status"] for c in cells_out)
    by_production = collections.Counter(str(c["production_use_allowed"]) for c in cells_out)
    by_ruling = collections.Counter(
        c["blocking_ruling"] for c in cells_out if c["blocking_ruling"]
    )
    by_open = collections.Counter(
        c["blocking_open_question"] for c in cells_out if c["blocking_open_question"]
    )
    by_problem = collections.Counter(p for c in cells_out for p in c["problem"])
    by_applied = collections.Counter(r for c in cells_out for r in c["rulings_applied"])
    by_c4 = collections.Counter(c["c4_disposition"] for c in cells_out if c.get("c4_disposition"))

    doc = collections.OrderedDict()
    doc["schema"] = "TAINT-REGISTER-v1"
    doc["status"] = (
        "evidence-status register for ROUTING-EVIDENCE-MAP-v0; this file reports "
        "the state of the evidence under the Controller rulings of 14 September 2026 "
        "and decides nothing"
    )
    doc["decides_nothing"] = True
    doc["no_launch_eligibility_here"] = (
        "This file contains no launch-eligibility judgement of any kind. Whether a "
        "cell may carry customer traffic is a Controller ruling plus a runtime "
        "decision. The runtime's policy profile decides which evidence_status "
        "values it will auto-route on."
    )
    doc["generated_by"] = "coordination/audits/tools/build_taint_register.py"
    doc["rulings"] = collections.OrderedDict(
        [
            ("record", RULINGS_RECORD),
            ("applied_on", "2026-09-14"),
            (
                "how_applied",
                "every human-acceptance number in the routing map is computed by "
                "recompute_elimination.py under the frozen rule, applied literally; "
                "this register reads those numbers back and names, per cell, the "
                "ruling that disposed of each problem the 10 September audit found",
            ),
            ("text", collections.OrderedDict((k, v) for k, v in RULINGS.items())),
        ]
    )
    doc["sources"] = collections.OrderedDict(
        [
            ("routing_evidence_map", MAP_PATH),
            ("routing_evidence_map_sha256", map_sha),
            ("routing_evidence_map_generated_utc", cmap.get("generated_utc")),
            ("routing_evidence_map_cell_count", cmap.get("cell_count")),
            ("recompute_tool", RECOMPUTE_PATH),
            ("recompute_tool_sha256", recompute_sha),
            ("elimination_rules", RULES_PATH),
            ("elimination_rules_sha256", rules_sha),
            ("recompute_audit", RECOMPUTE_AUDIT),
            ("audit_report_a", REPORT_A),
            ("audit_report_b", REPORT_B),
            ("controller_decisions", DECISIONS),
            ("rulings_record", RULINGS_RECORD),
        ]
    )
    doc["cell_count"] = len(cells_out)
    doc["settled_draw_floor"] = collections.OrderedDict(
        [
            ("value", MIN_SETTLED_DRAWS),
            (
                "basis",
                "Report A 'Missing scientific/product proof' item 4 and Report B "
                "part 4 item 1 with its P1 ('four draws per cell instead of two'). "
                "Quoted from the audits, not decided here. A settled draw is the "
                "first sending of a planned draw with a counted outcome (accept, "
                "reject, or a refusal / error counted as a failure); re-sends and "
                "smoke draws are never settled.",
            ),
        ]
    )
    doc["evidence_status_vocabulary"] = collections.OrderedDict(
        [
            (
                "clean_observed",
                "the literal frozen rule reproduces the number from the sealed files; "
                "every named problem touching the cell has been disposed of by a "
                "Controller ruling listed in rulings_applied and the cell recomputed; "
                "at least four settled draws",
            ),
            (
                "directional_only",
                "reproduces and every problem is disposed of, but fewer than four "
                "settled draws, so it must not carry a production decision on its own",
            ),
            (
                "awaiting_controller_ruling",
                "a named open ruling changes this cell's number, its keep/drop "
                "verdict, or whether it may be counted at all; no cell carries it "
                "since the rulings of 14 September 2026",
            ),
            (
                "method_tainted",
                "a named problem affects the number and no ruling disposes of it "
                "without new draws",
            ),
            ("insufficient", "not enough evidence to say anything"),
        ]
    )
    doc["problem_vocabulary"] = PROBLEM_VOCABULARY
    doc["problem_disposed_by"] = collections.OrderedDict(
        (p, PROBLEM_RULING[p]) for p in PROBLEM_VOCABULARY
    )
    doc["production_use_allowed_vocabulary"] = collections.OrderedDict(
        [
            ("true", "the evidence behind this cell is settled and reproduces"),
            ("manual_only", "a person must look before this cell decides anything"),
            (
                "false",
                "do not rest a route decision on this cell; every eliminated route "
                "is false with the reason 'eliminated on its question under the "
                "frozen rule (E-ids)'",
            ),
        ]
    )
    doc["c4_disposition_vocabulary"] = collections.OrderedDict(
        [
            (
                "recomputed_under_frozen_rule",
                "the number shown is the literal recompute under C-3 / C-6b / C-6d and stands",
            ),
            (
                "descriptive_only_pending_clean_replacement",
                "the recompute could not produce a frozen-rule number; the cell is "
                "descriptive product evidence only until cleanly replaced (no cell today)",
            ),
        ]
    )
    doc["notes"] = [
        collections.OrderedDict(
            [
                ("id", "NOTE-ROUTE-KEY-COLLISION"),
                (
                    "text",
                    "RESOLVED by C-6c. IMG-TEXT held two cells -- "
                    "flux-2-pro+C_composite_textless_base and flux-2-pro+code_overlay "
                    "-- with the SAME route_key ('flux-2-pro') and the SAME arm "
                    "('C_composite_textless_base'), resting on the same four trial "
                    "identities with two different verdicts (1 of 4 eliminated versus "
                    "4 of 4). C-6c rules that the two are DIFFERENT route mechanisms: "
                    "the model drawing the text (route identity flux-2-pro, "
                    "text_mechanism model_draws_text) and code composing the text on "
                    "a textless plate (route identity flux-2-pro+code_overlay, "
                    "text_mechanism deterministic_text_composition). The map now "
                    "carries distinct route_key values and a text_mechanism field on "
                    "every cell, the recompute tool groups the two judgings apart, "
                    "and a router keyed on (route_key, arm) gets one answer. The "
                    "cell KEYS are unchanged so consumers keep their references.",
                ),
                (
                    "cells",
                    [
                        "IMG-TEXT/flux-2-pro+C_composite_textless_base",
                        "IMG-TEXT/flux-2-pro+code_overlay",
                    ],
                ),
                ("blocking_ruling", None),
                ("resolved_by", "C-6c"),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "NOTE-THREE-DENOMINATORS"),
                (
                    "text",
                    "RESOLVED by C-3 and C-6b. The routing map used to run three "
                    "denominator conventions at once: the planned count (8), a double "
                    "count of failed plus re-sent draws (14, VID-I2V/wan-2.2-a14b-i2v), "
                    "and a count with the failed draws deleted (2, "
                    "VID-2SPK/kling-v3-pro-audio). There is now ONE convention "
                    "everywhere: the planned denominator, with the STRICT reading -- "
                    "the first sending of a draw is the one that counts, a failure "
                    "stays a failure, and a re-send is carried as descriptive only. "
                    "VID-I2V/wan-2.2-a14b-i2v is 2 of 8 with six counted failures; "
                    "VID-2SPK/kling-v3-pro-audio is 0 of 2 with two counted failures.",
                ),
                ("blocking_ruling", None),
                ("resolved_by", ["C-3", "C-6b"]),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "NOTE-BLINDNESS-BY-CONDUCT"),
                (
                    "text",
                    "Report B finding F-7. The two image rounds were blind by "
                    "construction: the true mapping was held outside the repository "
                    "and only a salted fingerprint was committed, and both "
                    "fingerprints re-compute. Every video and audio round was blind "
                    "by conduct only -- MAPPING.json sits beside the answer sheet, "
                    "the results files say commitment_verified: false, and the blind "
                    "copies the Controller actually watched were never sealed. A "
                    "clean_observed status on a video or audio cell therefore means "
                    "the ARITHMETIC reproduces; it does not mean the blinding can be "
                    "proved after the fact. Each cell carries "
                    "blinding_commitment_verified read from its own sealed results "
                    "file. This is not in the problem vocabulary and changes no "
                    "status here.",
                ),
                ("blocking_ruling", None),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "NOTE-UNTESTED-PRICING-SURFACE"),
                (
                    "text",
                    "Report B finding F-9. Every paid call behind this register ran "
                    "on fal, Vertex, Sarvam or ElevenLabs. No call has ever run on "
                    "the Gemini Developer API, yet the nano-banana-2, "
                    "nano-banana-pro, nano-banana-pro-edit and gemini-omni routes are "
                    "now priced against it. Where such a cell is clean_observed, the "
                    "ACCEPTANCE evidence is clean; the PRICE is quoted on a surface "
                    "that has never carried a call. C-13 is the smoke that would "
                    "close it.",
                ),
                ("blocking_ruling", None),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "NOTE-WHY-NO-METHOD-TAINTED-CELLS"),
                (
                    "text",
                    "No cell is method_tainted, and that is a statement about "
                    "REPAIRABILITY, not about safety. Every problem the closed "
                    "vocabulary can name has now been disposed of by a Controller "
                    "ruling (problem_disposed_by), and the recompute rebuilt every "
                    "number from the sealed bytes under the frozen rule, so no cell "
                    "is waiting on a ruling any more and none is beyond repair. What "
                    "the rulings did NOT do is re-test any route: where a route is "
                    "eliminated only because failures the run had classified as "
                    "infrastructure or request-shape faults are now counted "
                    "(replacement_needed: true -- VID-I2V/wan-2.2-a14b-i2v, "
                    "VID-2SPK/kling-v3-pro-audio+A_native, VID-T2V/kling-v3-pro-audio), "
                    "only a clean rerun under Controller item C-15 could put a new "
                    "number behind it. The generator's own guard refuses to run "
                    "against a changed map, so this file must be rebuilt deliberately "
                    "whenever the map is.",
                ),
                ("blocking_ruling", None),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "NOTE-REGISTRY-UNAFFECTED"),
                (
                    "text",
                    "This register covers the human-acceptance tier only. The 575 "
                    "deterministic Registry rows are untouched by every problem named "
                    "here: they never read a Controller verdict (C-4: 'Deterministic "
                    "Registry evidence is untouched'). Where one trial identity was "
                    "sent twice the Registry holds two rows for it, distinguishable "
                    "by run_ids; they must never be added together.",
                ),
            ]
        ),
    ]
    doc["open_questions"] = [
        collections.OrderedDict(
            [
                ("id", "OPEN-1"),
                (
                    "question",
                    "Is elimination per (route, question), as frozen rule E4 says, or "
                    "per (route, case), as two runs actually applied it?",
                ),
                ("raised_in", "%s -- Decision 4" % RECOMPUTE_AUDIT),
                ("status", "closed_by_ruling: C-6d"),
                (
                    "resolution",
                    "C-6d: 'Elimination is per (route, question), exactly as frozen E4.' "
                    "AUD-TTS/elevenlabs-v3-direct+native (4 of 6) and "
                    "VID-REF/veo-3.1-fast-ref2v+native (2 of 4) are kept on their "
                    "questions; the per-case advice in RR-11 and RR-12 stands.",
                ),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "OPEN-2"),
                (
                    "question",
                    "What is done about the three undeclared re-do runs "
                    "(vid-wan2-i2v, vid-2spk-kling, img-r1-composite), whose plans "
                    "record redo_of: null?",
                ),
                ("raised_in", "%s -- Decision 5" % RECOMPUTE_AUDIT),
                (
                    "status",
                    "closed: sealed files are never edited (C-1 'preserve history'); "
                    "the dispatch chain is carried by recompute_elimination.py and "
                    "this register",
                ),
                (
                    "note",
                    "img-r1-composite is not a re-do at all under C-6c: it is a "
                    "distinct mechanism (distinct_mechanism (C-6c) in the recompute "
                    "tool's section A). The other two are undeclared re-sends whose "
                    "attempts are listed per cell under descriptive_attempts.",
                ),
            ]
        ),
        collections.OrderedDict(
            [
                ("id", "OPEN-3"),
                (
                    "question",
                    "Were the four IMG-TEXT composite draws the same picture judged "
                    "twice, or two different pictures sharing one identity?",
                ),
                ("raised_in", "%s -- verification note" % RECOMPUTE_AUDIT),
                (
                    "why_unresolved",
                    "img-r1/RESULTS.yaml carries no artifact hash on any row, so the "
                    "sealed record cannot settle it. A byte comparison of the two "
                    "runs' artifact directories was outside the audit's scope.",
                ),
                ("related_ruling", "C-6c"),
                (
                    "status",
                    "moot_for_counting_under_C-6c; factual question about plate bytes "
                    "remains unresolved",
                ),
            ]
        ),
    ]
    doc["summary"] = collections.OrderedDict(
        [
            (
                "by_evidence_status",
                collections.OrderedDict(
                    (s, by_status.get(s, 0)) for s in STATUS_VOCABULARY
                ),
            ),
            (
                "by_production_use_allowed",
                collections.OrderedDict(
                    (k, by_production.get(k, 0))
                    for k in ("True", "manual_only", "False")
                ),
            ),
            (
                "by_blocking_ruling",
                collections.OrderedDict(sorted(by_ruling.items())),
            ),
            (
                "by_blocking_open_question",
                collections.OrderedDict(sorted(by_open.items())),
            ),
            (
                "by_rulings_applied",
                collections.OrderedDict((r, by_applied.get(r, 0)) for r in ALL_RULINGS),
            ),
            ("by_c4_disposition", collections.OrderedDict(sorted(by_c4.items()))),
            ("by_problem", collections.OrderedDict(sorted(by_problem.items()))),
            ("eliminated", sum(1 for c in cells_out if c["eliminated"])),
            (
                "replacement_needed",
                sum(1 for c in cells_out if c["replacement_needed"]),
            ),
        ]
    )
    doc["cells"] = cells_out

    yaml.add_representer(
        collections.OrderedDict,
        lambda dumper, data: dumper.represent_mapping(
            "tag:yaml.org,2002:map", data.items()
        ),
    )
    body = yaml.dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        width=100,
        allow_unicode=True,
    )
    return HEADER_COMMENT + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the committed register would change; write nothing",
    )
    args = parser.parse_args()

    root = repo_root()
    guard_map_version(root)
    text = build(root)

    out = os.path.join(root, OUT_PATH)
    if args.check:
        if not os.path.isfile(out):
            print("MISSING: %s" % OUT_PATH)
            return 1
        with open(out, "r", encoding="utf-8") as handle:
            current = handle.read()
        if current == text:
            print("UNCHANGED: %s" % OUT_PATH)
            return 0
        print("WOULD CHANGE: %s" % OUT_PATH)
        return 1

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d bytes)" % (OUT_PATH, len(text.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
