#!/usr/bin/env python3
"""Collect every Canon claim id a producer retrieved BY HAND on the accepted / recorded jobs.

    python3 canon/validation/hand_retrieved_claims.py [--write canon/validation/HAND-RETRIEVED-CLAIMS.yaml]

Reads the job branches on origin with `git grep` (no checkout), restricted to the files where a
producer records the claims it USED — stage documents, boards, copy decks, checker reports and
`canon-claims-used*` evidence — never search dumps (`canon-search-*`), never Canon copies, never
media. Each id is checked against the accepted corpus (`canon/knowledge/current/**` `sk_id:`).

This list is the coverage test for "Canon complete": a compiled pack, or the fetcher for that
brief, must deliver every id here — otherwise a machine-run job would not see what the hand-run
job used.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SK = re.compile(r"\bsk_[a-z0-9]+(?:_[a-z0-9]+)*_[0-9]{3,4}\b")
CHECK = re.compile(r"\b(?:CA|PA)-D[0-9]{1,2}\b")

# job → (branch, pathspecs where USED claims are recorded)
JOBS = OrderedDict([
    ("CUMINCO-CHOPSTICKS-003", ("origin/work/agency-job-cuminco-chopsticks-001",
        ["agency/jobs/*/stages/0*.md", "agency/jobs/*/stages/CHECK*.md", "agency/jobs/*/*.json", "agency/jobs/*/*.md", "agency/jobs/*/stages/evidence/canon-claims-used*"])),
    ("RENTOK-GAME-A-004", ("origin/work/agency-job-rentok-game-lane-a-001",
        ["agency/jobs/*/stages/0*.md", "agency/jobs/*/stages/CHECK*.md", "agency/jobs/*/*.json", "agency/jobs/*/*.md", "agency/jobs/*/stages/evidence/canon-claims-used*"])),
    ("RENTOK-GAME-B-005", ("origin/work/agency-job-rentok-game-lane-b-001",
        ["agency/jobs/*/stages/0*.md", "agency/jobs/*/stages/CHECK*.md", "agency/jobs/*/*.json", "agency/jobs/*/*.md", "agency/jobs/*/stages/evidence/canon-claims-used*"])),
    ("RENTOK-CREATIVE-QUALITY-001", ("origin/work/experiment-rentok-creative-quality-001",
        ["experiments/*/0*.md", "experiments/*/treatments/*/*.md", "experiments/*/treatments/*/*.json", "experiments/*/evaluation/*.md"])),
    ("RENTOK-GAME-V2-006", ("origin/work/agency-job-rentok-game-v2-001",
        ["agency/jobs/*/stages/0*.md", "agency/jobs/*/stages/CHECK*.md", "agency/jobs/*/*.json", "agency/jobs/*/*.md", "agency/jobs/*/stages/evidence/canon-claims-used*"])),
    ("MOKOBARA-ODYSSEY-007", ("origin/work/agency-job-mokobara-odyssey-001",
        ["agency/jobs/*/stages/0*.md", "agency/jobs/*/stages/CHECK*.md", "agency/jobs/*/*.json", "agency/jobs/*/*.md", "agency/jobs/*/stages/evidence/canon-claims-used*"])),
])


def corpus_ids() -> tuple[set, dict]:
    ids, by_source = set(), {}
    for f in (REPO / "canon" / "knowledge" / "current").rglob("source-knowledge.yaml"):
        found = re.findall(r"^\s*(?:-\s*)?sk_id:\s*['\"]?(sk_[A-Za-z0-9_]+)", f.read_text(encoding="utf-8", errors="replace"), re.M)
        ids.update(found)
        for i in found:
            by_source[i] = f.parent.name
    return ids, by_source


def grep_branch(ref: str, pathspecs: list[str]) -> dict:
    """id → sorted list of files it appears in (text files only)."""
    # git grep is POSIX ERE (no \b): grep loosely, then keep only exact matches of SK / CHECK
    out = subprocess.run(["git", "grep", "-I", "-noE", "sk_[a-z0-9_]+|(CA|PA)-D[0-9]+", ref, "--", *pathspecs],
                         capture_output=True, text=True, cwd=REPO)
    hits: dict[str, set] = {}
    for line in out.stdout.splitlines():
        # ref:path:lineno:match
        try:
            _, path, _, match = line.split(":", 3)
        except ValueError:
            continue
        m = SK.fullmatch(match) or CHECK.fullmatch(match)
        if not m:
            continue
        hits.setdefault(match, set()).add(path.split("/")[-1])
    return {k: sorted(v) for k, v in hits.items()}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", default=None)
    a = ap.parse_args(argv)
    ids, by_source = corpus_ids()
    lines = ["# HAND-RETRIEVED-CLAIMS — every Canon claim id a producer cited on a recorded job, by job.",
             "# Generated by canon/validation/hand_retrieved_claims.py from the job branches on origin (used-claim files only; no search dumps).",
             "# The coverage test for Canon completion: each `sk_` id must be delivered by a compiled pack or the fetcher for that brief.",
             f"corpus_accepted_ids: {len(ids)}", "jobs:"]
    all_sk, unknown_all = set(), set()
    for job, (ref, specs) in JOBS.items():
        hits = grep_branch(ref, specs)
        sk = sorted(k for k in hits if k.startswith("sk_"))
        checks = sorted(k for k in hits if not k.startswith("sk_"))
        unknown = [k for k in sk if k not in ids]
        all_sk.update(k for k in sk if k in ids)
        unknown_all.update(unknown)
        lines += [f"  {job}:", f"    branch: {ref}", f"    sk_ids_cited: {len(sk)}", f"    compiled_check_ids_cited: {len(checks)}",
                  f"    unknown_ids: {unknown}" if unknown else "    unknown_ids: []", "    claims:"]
        for k in sk:
            src = by_source.get(k, "UNKNOWN")
            lines.append(f"      - {{id: {k}, source: {src}, in: {hits[k]}}}")
        print(f"{job:<30} sk {len(sk):>3}  checks {len(checks):>2}  unknown {len(unknown)}", file=sys.stderr)
    srcs = sorted({by_source[i] for i in all_sk})
    lines += ["summary:", f"  distinct_sk_ids_across_jobs: {len(all_sk)}", f"  distinct_sources: {len(srcs)}", f"  sources: {srcs}",
              f"  unknown_ids_across_jobs: {sorted(unknown_all)}"]
    text = "\n".join(lines) + "\n"
    if a.write:
        Path(a.write).write_text(text, encoding="utf-8")
        print(f"wrote {a.write}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
