#!/usr/bin/env python3
"""Deterministic ad/card composer for the Upwork intro pilot.

Every glyph is rasterised by hb-view from an explicit font FILE + face index (the mechanism the
Devanagari-exactness battery pinned: no family lookup, no fallback, byte-identical output), then
composited with Pillow. Nothing here calls a model. Devanagari is never generated by a model.

Archetype implemented: "The Ledge" (docs/2026-09-14-ad-design-direction.md §2/§3, Direction 1):
photographic plate on top, solid brand panel below, product overlapping the seam, offer pill on
the seam, left-aligned copy column, filled CTA button, logo lockup bottom-right, legal at the edge.
"""
from __future__ import annotations

import hashlib
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

FONTS = {
    "didot": ("/System/Library/Fonts/Supplemental/Didot.ttc", 0),
    "didot_bold": ("/System/Library/Fonts/Supplemental/Didot.ttc", 2),
    "hn": ("/System/Library/Fonts/HelveticaNeue.ttc", 0),
    "hn_medium": ("/System/Library/Fonts/HelveticaNeue.ttc", 10),
    "hn_bold": ("/System/Library/Fonts/HelveticaNeue.ttc", 1),
    "hn_light": ("/System/Library/Fonts/HelveticaNeue.ttc", 7),
    "dev_bold": ("/System/Library/Fonts/Kohinoor.ttc", 3),
    "dev_semibold": ("/System/Library/Fonts/Kohinoor.ttc", 2),
    "dev_medium": ("/System/Library/Fonts/Kohinoor.ttc", 1),
    "dev_regular": ("/System/Library/Fonts/Kohinoor.ttc", 0),
}

_CACHE = Path(tempfile.gettempdir()) / "adcomp-glyphs"
_CACHE.mkdir(exist_ok=True)


def _hex_to_rgba(h: str, alpha: int = 255) -> tuple[int, int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), alpha)


def text(s: str, font: str, size_px: int, colour: str, alpha: int = 255) -> Image.Image:
    """RGBA glyph image on a transparent ground, via hb-view. Cached by content hash."""
    file, face = FONTS[font]
    key = hashlib.sha256(f"{s}|{file}|{face}|{size_px}|{colour}|{alpha}".encode()).hexdigest()[:24]
    out = _CACHE / f"{key}.png"
    if not out.exists():
        unicodes = ",".join(f"U+{ord(c):04X}" for c in s)
        r, g, b, _ = _hex_to_rgba(colour)
        fg = f"#{r:02X}{g:02X}{b:02X}{alpha:02X}"
        cmd = ["hb-view", file, f"--face-index={face}", f"--unicodes={unicodes}",
               f"--font-size={size_px}", "--margin=0", "--background=#00000000",
               f"--foreground={fg}", "-O", "png", "-o", str(out)]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0 or not out.exists():
            raise RuntimeError(f"hb-view failed for {s!r}: {res.stderr[:200]}")
    im = Image.open(out).convert("RGBA")
    return im


def text_width(s: str, font: str, size_px: int) -> int:
    return text(s, font, size_px, "#000000").width


def paste(base: Image.Image, im: Image.Image, x: int, y: int) -> None:
    base.alpha_composite(im, (int(x), int(y)))


def rounded_rect(size: tuple[int, int], radius: int, colour: str, alpha: int = 255) -> Image.Image:
    im = Image.new("RGBA", size, (0, 0, 0, 0))
    ImageDraw.Draw(im).rounded_rectangle([0, 0, size[0] - 1, size[1] - 1], radius=radius, fill=_hex_to_rgba(colour, alpha))
    return im


def pill(label: str, font: str, size_px: int, fill: str, ink: str, pad_x: float = 0.9, pad_y: float = 0.55) -> Image.Image:
    g = text(label, font, size_px, ink)
    px, py = int(size_px * pad_x), int(size_px * pad_y)
    w, h = g.width + 2 * px, g.height + 2 * py
    im = rounded_rect((w, h), h // 2, fill)
    paste(im, g, px, py)
    return im


def button(label: str, font: str, size_px: int, fill: str, ink: str, min_w: int = 0) -> Image.Image:
    g = text(label, font, size_px, ink)
    px, py = int(size_px * 1.4), int(size_px * 0.75)
    w, h = max(g.width + 2 * px, min_w), g.height + 2 * py
    im = rounded_rect((w, h), int(size_px * 0.35), fill)
    paste(im, g, (w - g.width) // 2, py)
    return im


def strike(g: Image.Image, colour: str, thickness: int) -> Image.Image:
    im = g.copy()
    d = ImageDraw.Draw(im)
    y = int(im.height * 0.55)
    d.line([(0, y), (im.width, y)], fill=_hex_to_rgba(colour), width=thickness)
    return im


@dataclass
class Brand:
    primary: str = "#1F4B3F"
    accent: str = "#D9A441"
    cream: str = "#F4EFE6"
    wordmark: str = "Aarohi"
    display: str = "didot"          # Latin display face
    textface: str = "hn"            # Latin text face
    textface_bold: str = "hn_medium"


@dataclass
class Copy:
    lang: str                        # "en" | "hi"
    headline: list[str]              # lines, set for sense (no orphans)
    pill: str
    product: str
    price: str
    was: str
    code: str
    cta: str
    legal: str
    # Devanagari faces are used for every string when lang == "hi"
    fonts: dict = field(default_factory=dict)

    def f(self, role: str, brand: Brand) -> str:
        if self.lang == "hi":
            return {"display": "dev_bold", "text": "dev_regular", "bold": "dev_semibold"}[role]
        return {"display": brand.display, "text": brand.textface, "bold": brand.textface_bold}[role]


AAROHI_EN = Copy("en", ["Glass skin", "in three weeks"], "Flat 30% off", "Radiance Serum", "₹1,299", "₹1,855",
                 "Code GLOW30", "Shop now", "Offer valid till 30 September. T&C apply.")
# Origination, not translation (sk_nnn_0052): a line an Indian copywriter would write, not a gloss.
AAROHI_HI = Copy("hi", ["निखार,", "तीन हफ़्तों में"], "फ़्लैट 30% छूट", "रेडियंस सीरम", "₹1,299", "₹1,855",
                 "कोड GLOW30", "अभी ख़रीदें", "ऑफ़र 30 सितंबर तक। नियम व शर्तें लागू।")


FORMATS = {
    "4x5": (1080, 1350),
    "1x1": (1080, 1080),
    "9x16": (1080, 1920),
    "wa": (800, 800),
}


def fit_plate(plate: Image.Image, W: int, H_plate: int, anchor_y: float = 0.5) -> Image.Image:
    """Cover-fit the plate into W x H_plate, keeping the horizontal centre and a chosen vertical anchor."""
    pw, ph = plate.size
    scale = max(W / pw, H_plate / ph)
    nw, nh = int(pw * scale + 0.5), int(ph * scale + 0.5)
    p = plate.resize((nw, nh), Image.LANCZOS)
    x0 = (nw - W) // 2
    y0 = int((nh - H_plate) * anchor_y)
    return p.crop((x0, y0, x0 + W, y0 + H_plate))


def ledge(plate: Image.Image, copy: Copy, brand: Brand, fmt: str = "4x5",
          build: float = 1.0) -> Image.Image:
    """Compose the Ledge archetype. `build` in [0,1] reveals elements in hierarchy order so the same
    function can render the 'ad builds itself' animation frames deterministically. The headline
    size shrinks until every block clears its neighbour (no overlaps, ever)."""
    W, H = FORMATS[fmt]
    is_wa = fmt == "wa"
    seam = {"4x5": 0.60, "1x1": 0.52, "9x16": 0.58, "wa": 0.52}[fmt]
    ui_bot = int(H * 0.177) if fmt == "9x16" else 0            # Stories UI reserve
    plate_h = int(H * seam)
    m = int(W * 0.065)
    hl = int(W * (0.095 if is_wa else 0.082))
    while True:
        layout = _ledge_layout(W, H, plate_h, ui_bot, m, hl, copy, brand, is_wa)
        if layout["fits"] or hl < int(W * 0.05):
            break
        hl -= 2
    canvas = Image.new("RGBA", (W, H), _hex_to_rgba(brand.primary))
    paste(canvas, fit_plate(plate, W, plate_h, anchor_y=0.35), 0, 0)
    shadow = Image.new("RGBA", (W, 40), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rectangle([0, 0, W, 12], fill=(0, 0, 0, 55))
    shadow = shadow.filter(ImageFilter.GaussianBlur(10))
    paste(canvas, shadow, 0, plate_h - 24)
    if build >= 0.15:
        paste(canvas, Image.new("RGBA", (W, H - plate_h), _hex_to_rgba(brand.primary)), 0, plate_h)
    for thr, im, x, y in layout["items"]:
        if build >= thr:
            paste(canvas, im, x, y)
    return canvas


def _ledge_layout(W, H, plate_h, ui_bot, m, hl, copy, brand, is_wa):
    items = []
    pill_im = pill(copy.pill, copy.f("bold", brand), int(hl * 0.42), brand.accent, brand.primary)
    items.append((0.30, pill_im, m, plate_h - pill_im.height // 2))
    y = plate_h + pill_im.height // 2 + int(hl * 0.50)
    for line in copy.headline:
        g = text(line, copy.f("display", brand), hl, brand.cream)
        items.append((0.45, g, m, y))
        y += int(hl * 1.10)
    y += int(hl * 0.22)
    sub = int(hl * 0.42)
    if not is_wa:
        x = m
        g = text(copy.product, copy.f("text", brand), sub, brand.cream); items.append((0.60, g, x, y)); x += g.width + int(sub * 0.9)
        g = text(copy.price, copy.f("bold", brand), sub, brand.accent); items.append((0.60, g, x, y)); x += g.width + int(sub * 0.7)
        g = strike(text(copy.was, copy.f("text", brand), sub, brand.cream, alpha=170), brand.cream, max(2, sub // 14)); items.append((0.60, g, x, y)); x += g.width + int(sub * 0.9)
        g = text(copy.code, copy.f("text", brand), sub, brand.cream, alpha=200); items.append((0.60, g, x, y))
        sub_right = x + g.width
        y += int(sub * 1.15) + int(hl * 0.45)
    else:
        sub_right = m
        y += int(hl * 0.2)
    btn = button(copy.cta, copy.f("bold", brand), int(hl * 0.40), brand.accent, brand.primary)
    logo = text(brand.wordmark, "didot", int(hl * 0.40), brand.cream)
    leg = text(copy.legal, copy.f("text", brand), max(18, int(hl * 0.19)), brand.cream, alpha=150)
    leg_y = H - ui_bot - leg.height - int(hl * 0.35)
    row_y = y
    fits = (row_y + btn.height + int(hl * 0.35) <= leg_y) and (sub_right <= W - m)
    items.append((0.75, btn, m, row_y))
    items.append((0.90, logo, W - m - logo.width, row_y + (btn.height - logo.height) // 2))
    items.append((1.0, leg, m, leg_y))
    return {"fits": fits, "items": items, "hl": hl}


# ---------------------------------------------------------------------------------------------
# 16:9 cards for the film (neutral studio system, not the demo brand)

STUDIO = Brand(primary="#17201C", accent="#B88A2E", cream="#F5F1EA", wordmark="Adwisely",
               display="didot", textface="hn", textface_bold="hn_medium")


def card(lines: list[tuple[str, str, int, str]], size=(1920, 1080), ground: str = "#F5F1EA",
         align: str = "left", margin: float = 0.09, gap: float = 0.35, valign: str = "center") -> Image.Image:
    """Solid-ground card. lines = [(text, font, size_px, colour), ...]. Left-aligned by default
    (design doc: centre only when line widths are within ~15%)."""
    W, H = size
    im = Image.new("RGBA", (W, H), _hex_to_rgba(ground))
    glyphs = [text(t, f, s, c) for (t, f, s, c) in lines]
    total = sum(g.height for g in glyphs) + sum(int(s * gap) for (_, _, s, _) in lines[:-1])
    y = (H - total) // 2 if valign == "center" else int(H * 0.12)
    m = int(W * margin)
    for g, (_, _, s, _) in zip(glyphs, lines):
        x = m if align == "left" else (W - g.width) // 2
        paste(im, g, x, y)
        y += g.height + int(s * gap)
    return im


if __name__ == "__main__":
    import sys
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("adcomp-selftest")
    out.mkdir(parents=True, exist_ok=True)
    # Self-test on a flat stand-in plate: proves fonts, shaping and layout without any model call.
    plate = Image.new("RGBA", (1080, 1350), (214, 200, 186, 255))
    d = ImageDraw.Draw(plate)
    d.rectangle([460, 420, 620, 860], fill=(90, 70, 60, 255))   # stand-in bottle
    for fmt in FORMATS:
        ledge(plate, AAROHI_EN, Brand(), fmt).convert("RGB").save(out / f"selftest-en-{fmt}.png")
    ledge(plate, AAROHI_HI, Brand(), "4x5").convert("RGB").save(out / "selftest-hi-4x5.png")
    card([("Your brief.", "didot", 150, "#17201C"), ("One photo. One line.", "hn", 64, "#17201C")]).convert("RGB").save(out / "selftest-card.png")
    print("ok", out)
